### PR TITLE
add assembled STL models

### PR DESCRIPTION
**Pull request by yatli**
image

image

### CODE REVIEW

**Comment by jmamma** [comment]
Just back from vacation. Will review over the weekend.

**Comment by yatli** [comment]
Note, the OLED display position may be off. See #5

**Comment by jmamma** [comment]
> Note, the OLED display position may be off. See #5

Do you mean, the 3D model does not match the OLED alignment?

**Comment by yatli** [comment]
I'm not sure of the root cause. The 3D model of the board, OLED and the chassis mate very well in Solidworks, but the actual product I receive exhibits mismatch. Note I have to manually mill the display window a bit to fit the OLED.

The MegaCommand board model should be accurate because it is computationally created.
The error may come from the following sources:
1. Faulty OLED modeling, which leads to faulty chassis modeling. I've uploaded the OLED model here: https://grabcad.com/library/oled-display-128x32-2-3-inch-1
2. The engineer doing flanging/laser cut misunderstood my drawing
3. The sheetmetal plate reacts differently than I understand when it bends -- the display window is measured from the left edge -- despite the fact that the panel plate is not bended in left-right direction, the engineer may have "overridden" my dimensions 0.0
4. Random error caused by a butterfly

**Comment by jmamma** [comment]
Any progress here @yatli ? 

I will merge this models when you are satisfied.

**Comment by yatli** [comment]
Hi @jmamma,

Just want to let you know I have not disappeared. I'll post updates after I manually measure the dimensions.

**Comment by yatli** [comment]
The schematics of the OLED module I found online is somewhat inaccurate.
The pinholes are off by ~2mm to the edge.
I've measured that PIN1 center should be ~9.06mm from the PCB left edge, which, after hierarchical update, ends up in the exact rendering as my problematic actual chasis:

image

**Comment by yatli** [comment]
updates are pushed and I think it's ready for a merge now!

**Comment by jmamma** [comment]
What did you use to generate the STL files ?

**Comment by yatli** [comment]
I create the models with solidworks, and it supports saving to stl files.

**Pull request merged**
